### PR TITLE
Transport running in ReceiveOnly transaction mode

### PR DESCRIPTION
**Pull request by Scooletz**
This PR changes the transport transaction mode to `TransportTransactionMode.ReceiveOnly`

Solves #87

### CODE REVIEW

**Comment by WilliamBZA** [comment]
I don't have the context to review the implications of this, but the code looks fine ¯\_(ツ)_/¯

**Comment by Scooletz** [comment]
Admins of this repo should merge it.

**Comment by Scooletz** [comment]
I see that there's an unreported check `default`. I took a look at integrations for this repo, found nothing unusual. I kicked the build and waiting for the status.

**Comment by Scooletz** [comment]
Ah, could @Particular/servicecontrol-maintainers put a review it and add a review and merge it? It looks like this is the `default  check` that we're missing.

**Comment by tmasternak** [comment]
@Scooletz but @SzymonPobiega is member of @Particular/servicecontrol-maintainers

**Comment by SzymonPobiega** [comment]
What @WilliamBZA said. I think it is safe to assume the repo ownership belongs to the Wave until the Wave flattens out and creates proper maintainer groups or tricks existing groups into supporting repos like this one.

**Comment by WilliamBZA** [comment]
Doesn't answer the question of why the default is waiting. @Particular/deployment-maintainers any ideas?

**Comment by SzymonPobiega** [comment]
@WilliamBZA Let me put my depl maintainer 🎩 on.

I have no idea why is that. I've never seen something like this before. I advise to ignore this and just merged. Ping us again if it happens again in future.

**Comment by kbaley** [comment]
The default check is my fault. That was a check on the original `Build` build config to make sure it passed before deploying. I didn't update these checks when I migrated the project over to the new templates. It's fixed now.

For reference: https://github.com/Particular/Deployment/tree/master/tc-project-setup#setup-github-integration

**Pull request merged**
