### PR TITLE
Smoke tests

### PR DESCRIPTION
**Pull request by Scooletz**
This PR introduces a set of end to end tests that shows SC.Monitoring + Metrics on the endpoint side working with different transports:
- ASQ
- ASB
- RabbitMQ
- Learning Transport
- SQL Server

### CODE REVIEW

**Comment by Scooletz** [comment]
How should we proceed with these @Particular/servicecontrol-maintainers ?

**Comment by SzymonPobiega** [comment]
@Scooletz you mean you want a review?

**Comment by Scooletz** [comment]
Nope @SzymonPobiega Let me clarify.
 This PR provides a few suites of tests that cover 5 transports in regards to having SC.Monitoring smoke tested. They are not configured in our build environment, so they cannot be included in the usual test suite. Frankly speaking, I don't think they should. They were valuable just to show that we don't break on any transport, that we did not drop the ball anywhere.
Having this said, I'm looking for the insight of the maintainers whether, and if yes, how, they should be included? Or maybe we're just fine with leaving them as they are?

**Comment by Scooletz** [comment]
Ping @Particular/servicecontrol-maintainers 
What do we do with it?

**Comment by boblangley** [comment]
Smoke tests can be left as they are.

**Comment by Scooletz** [comment]
I'll update this branch and ping you when it's green and ready to get merged @boblangley

**Comment by Scooletz** [comment]
Updated @Particular/servicecontrol-maintainers 
If "squash and merge" is possible, please do it. It contains this clumsy update commit from develop

**Comment by WilliamBZA** [comment]
@Scooletz I will run with this one. I'll rebase and merge. Once it's merged I'll create a separate issue to automate the transport testing in the future.

**Comment by Scooletz** [comment]
🎉

**Pull request merged**
