### PR TITLE
Upgrade transports to latest

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Wow, the old style `csproj` are such a pain in the back to review when it comes to dependency upgrades. Monitoring should have a maintenance release to migrate to the SDK style if possible

**Comment by tmasternak** [comment]
@SzymonPobiega I'm glad you mention this https://github.com/Particular/ServiceControl.Monitoring/issues?q=is%3Aissue+is%3Aopen+label%3Amaintenance-release ;)

**Comment by SzymonPobiega** [comment]
@tmasternak do you want me to talk to some people in the KTLO? I have some contacts there :P

**Comment by tmasternak** [comment]
@SzymonPobiega that would be much appreciated :).

**Pull request merged**
