### PR TITLE
Learning Transport Support

### PR DESCRIPTION
**Pull request by mikeminutillo**
Enables the Monitoring Instance to run against the Learning Transport. To use it, add the following to the config file:

```xml
<configuration>
  <appSettings>
    <add key="Monitoring/TransportType" value="NServiceBus.ServiceControlLearningTransport, ServiceControl.Transports.LearningTransport" />
  </appSettings>
  <connectionStrings>
    <add name="NServiceBus/Transport" connectionString="C:\Temp\LearningTransportTest" />
  </connectionStrings>
</configuration>
```

### CODE REVIEW

**Comment by Scooletz** [comment]
Why wasn't it able to run on the learning transport before? I'm sorry, but I'm not familiar with this transport.

**Comment by mikeminutillo** [comment]
@Scooletz the Learning Transport, used outside of a Visual Studio solution, needs to be configured with a base path. It does not read connection strings by default.

**Comment by mikeminutillo** [comment]
This can be merged as soon as the reviewers are happy :)

**Comment by Scooletz** [comment]
If I'm happy and I know it merge this PR.
If I'm happy and I know it ...

**Pull request merged**
